apiVersion: v1 # it's version of replication controller 
kind: ReplicationController # replication controller defination file
metadata:
  name: myapp-replicationController
  labels:
    tier: tst-lab-rc
spec: 
  replicas: 3 # no.of replicas
  template: 
  # this section we mention POD Spec info
    metadata: 
      name: redis
      labels:
        tier: tst-lab
    spec:
      containers:
      - name: redis
        image: redis