apiVersion: v1
kind: Namespace
metadata:
  name: dev

## it will create new namespace with name "dev"

# kubectl create -f namespace.yml
#         or
#  kubectl create namespace dev   => it simpliy create the namespace "dev"

## kubectl get pods --> this command displays the pods in the default namespace

## kubectl get pods --namespace=dev --> it displays the pods in the "dev" namespace

## to change default namespace to "dev" namespace run following command
# kubectl config set-context $(kubectl config current-context) --namespace=dev


## to get all pods in all namespaces

## kubectl get pods --all-namespaces